version: '3.8'

services:
  llm-microservice:
    build: .
    container_name: llm_microservice
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: always
